apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.56.4
    path: /nfs

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: cicflowmeter
spec:
  hostNetwork: true
  containers:
    - name: cicflowmeter-container
      image: redmors/cicflowmeter:1.1.1
      volumeMounts:
        - name: nfs-storage
          mountPath: /nfs
      securityContext:
        privileged: true
  volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-pcap
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.56.4
    path: /nfs/pcap

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-pcap
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: tcpdump
spec:
  hostNetwork: true
  containers:
    - name: tcpdump
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args: ["apk update && apk add tcpdump && tcpdump -i cni0 -w /captures/capture-%H%M.pcap -G 60"]
      volumeMounts:
        - name: nfs-storage
          mountPath: /captures
      securityContext:
        privileged: true
  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: nfs-pvc-pcap
