---

apiVersion: v1
kind: Namespace
metadata:
  name: ids

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-cicflowmeter
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.56.5
    path: /nfs

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-cicflowmeter
  namespace: ids
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: cicflowmeter
  namespace: ids
spec:
  hostNetwork: true
  containers:
    - name: cicflowmeter-container
      image: redmors/cicflowmeter:1.2.9
      volumeMounts:
        - name: nfs-storage
          mountPath: /nfs
      securityContext:
        privileged: true
  volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc-cicflowmeter

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-tcpdump
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.56.5
    path: /nfs

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-tcpdump
  namespace: ids
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: tcpdump
  namespace: ids
spec:
  hostNetwork: true
  containers:
    - name: tcpdump
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args: ["apk update && apk add tcpdump && tcpdump -i cni0 -w /nfs/pcap/capture-%Y-%m-%d_%H:%M:%S.pcap -G 15"]
      volumeMounts:
        - name: nfs-storage
          mountPath: /nfs
      securityContext:
        privileged: true
  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: nfs-pvc-tcpdump

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-ids
  namespace: ids
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-ids
  template:
    metadata:
      labels:
        app: ml-ids
    spec:
      containers:
        - name: ml-ids
          image: redmors/ml-ids-classifier:1.1.0
          ports:
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: ml-ids
  namespace: ids
spec:
  selector:
    app: ml-ids
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30500

---

apiVersion: v1
kind: Namespace
metadata:
  name: app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: app
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-sim
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-sim
  template:
    metadata:
      labels:
        app: user-sim
    spec:
      containers:
        - name: user-sim
          image: redmors/user-sim:0.0.1
          imagePullPolicy: Always
